apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-cezhfh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-cezhfh
    app.kubernetes.io/part-of: jvm-build-suite-application-exen
  name: jvm-build-suite-component-cezhfh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-cezhfh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-cezhfh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-xtxu-tenant/jvm-build-suite-application-exen/jvm-build-suite-component-cezhfh@sha256:6d3f005e676731872a75e7923fb8f7d8aaf7af2d86861a9984a01d2f15a8fd5e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
